### ISSUE TITLE
Got ''dict' object has no attribute 'url'' error

### ISSUE THREAD

**Issue by mutoulbj** [voronind/django-awesome-avatar#4]
Hi,I use django1.6 and modelform to change avatar,when i submit the form I got the "dict has no attribute 'url'" error and `<ul class="errorlist"><li>avatar<ul class="errorlist"><li>This field cannot be blank.</li></ul></li></ul>`。  

Anything error  I made? Thanks.

**Comment by scrua** [comment]
Add in tag form parameter enctype="multipart/form-data".
